#!/bin/bash

shopt -s nocasematch

SYMFONY_CONSOLE=/var/www/bin/console
if [[ -f "$SYMFONY_CONSOLE" ]]; then
  php ${SYMFONY_CONSOLE} cache:clear
  composer run-script --no-dev auto-scripts
  php ${SYMFONY_CONSOLE} --no-interaction doctrine:migrations:migrate
fi

chown -R www-data:www-data /var/www/var

shopt -u nocasematch

service cron start
apache2-foreground
